### PR TITLE
In test/NVQPP renamed the test_[0-6].cpp to issue_#.cpp

### PR DESCRIPTION
**Pull request by ZyphrFlaw**
### Description

Renamed test[0-6].cpp files in test/NVQPP as issue_#.cpp 
# being the issue number.

### CODE REVIEW

**Review by ZyphrFlaw — COMMENTED** [review]
I have read the Contributor License Agreement and I hereby accept the Terms.

**Review by schweitzpgi — COMMENTED** [review]
Are the numbers used here the PR (fix) numbers? They don't seem to correspond to the issue numbers from the list in #323.

**Comment by schweitzpgi** [comment]
Looks like your email address is missing (for the CLA bot).

**Comment by ZyphrFlaw** [comment]
I opened the test file and gave the issue number present at the top. 
image

I think I made some mistake; I'll use the issue number in the list #323

**Comment by schweitzpgi** [comment]
> I have read the Contributor License Agreement and I hereby accept the Terms.

There is a link in https://github.com/NVIDIA/cuda-quantum/pull/388#issuecomment-1629621585 that shows how to update your email address for the CLA bot to be happy.

**Comment by ZyphrFlaw** [comment]
Already updated the email but still CLA bot is unhappy.

**Pull request closed without merging**
