### PR TITLE
Identify incomplete processing in OQC server helper

### PR DESCRIPTION
**Pull request by owen-oqc**
json null previously matched against c++ NULL 0. This allowed the future to terminate and fetch results before processing had finished.

### CODE REVIEW

**Comment by owen-oqc** [comment]
> Thanks, @owen-oqc. Do you think this change can explain these two nightly integration test failures?
> 
> 1. https://github.com/NVIDIA/cuda-quantum/actions/runs/6346699077
> 2. https://github.com/NVIDIA/cuda-quantum/actions/runs/6515196721
> 
> The error for those runs looked like this:
> 
> ```shell
> [2023-09-29 03:28:12.135] [info] [OQCServerHelp.cpp:267] Null results received; fetching detailed error message here: https://sandbox.qcaas.oqc.app/tasks/225a5665-264f-4730-8400-e1cb10c3fc07/error
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  OQC backend error message: {"task_error":null}
> /__w/_temp/54c4d008-0960-46fa-b317-d7d26c92b688.sh: line 10:  5857 Aborted                 (core dumped) ./a.out
> ```

Yes exactly this

**Comment by bmhowe23** [comment]
> Yes exactly this

Great! If you merge the latest from main into your branch, we can get this merged after that.

**Pull request merged**
