### PR TITLE
Improve build - Link to correct version of custatvec libs

### PR DESCRIPTION
**Pull request by hamidelmaazouz**
### Description

This PR introduces a combined solution for the issues: https://github.com/NVIDIA/cuda-quantum/issues/83 and https://github.com/NVIDIA/cuda-quantum/issues/87.

It tweaks the build script `build_cudaq.sh` and `runtime/nvqir/custatevec/CMakeLists.txt` to systematically link against the correct version/location of `cuStateVec` depending on which CUDA version is installed on the system.

### CODE REVIEW

**Comment by hamidelmaazouz** [comment]
I have read the Contributor License Agreement and I hereby accept the Terms.

**Comment by hamidelmaazouz** [comment]
> Thank you for the contribution @hamidelmaazouz
> 
> There is another issue with the latest release of cuQuantum as documented in #83. I think that we should consider a combined solution here that will address both your issue and the issue there. I would suggest that you update this PR with the following diff
> 
> ```diff
> diff --git a/runtime/nvqir/custatevec/CMakeLists.txt b/runtime/nvqir/custatevec/CMakeLists.txt
> index b3dd5b0..d9b9250 100644
> --- a/runtime/nvqir/custatevec/CMakeLists.txt
> +++ b/runtime/nvqir/custatevec/CMakeLists.txt
> @@ -10,6 +10,21 @@ set(INTERFACE_POSITION_INDEPENDENT_CODE ON)
>  set (CMAKE_ENABLE_EXPORTS TRUE)
>  message (STATUS "CUSTATEVEC_ROOT and CUDA_FOUND - building custatevec NVQIR backend.")
>  
> +set (CUSTATEVEC_LIBDIR lib)
> +if (EXISTS ${CUSTATEVEC_ROOT}/lib64)
> +  set (CUSTATEVEC_LIBDIR lib64)
> +endif()
> +
> +string(REPLACE "." ";" CUDA_VERSION_LIST ${CMAKE_CUDA_COMPILER_VERSION})
> +list(GET CUDA_VERSION_LIST 0 CUDA_MAJOR_VERSION)
> +
> +find_library(CUSTATEVEC_STATIC_LIB
> +        NAMES custatevec_static
> +        HINTS 
> +          ${CUSTATEVEC_ROOT}/${CUSTATEVEC_LIBDIR} 
> +          ${CUSTATEVEC_ROOT}/${CUSTATEVEC_LIBDIR}/${CUDA_MAJOR_VERSION}
> + )
> +
>  macro (nvqir_create_cusv_plugin LIBRARY_NAME SOURCE_FILENAME) 
>    add_library(${LIBRARY_NAME} SHARED ${SOURCE_FILENAME})
>  
> @@ -17,10 +32,6 @@ macro (nvqir_create_cusv_plugin LIBRARY_NAME SOURCE_FILENAME)
>      PRIVATE .. ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES} ${CMAKE_SOURCE_DIR}/runtime/common
>      ${CUSTATEVEC_ROOT}/include)
>  
> -  set (CUSTATEVEC_LIBDIR lib)
> -  if (EXISTS ${CUSTATEVEC_ROOT}/lib64)
> -    set (CUSTATEVEC_LIBDIR lib64)
> -  endif()
>  
>    target_link_libraries(${LIBRARY_NAME} PRIVATE fmt::fmt-header-only cudaq-common
>                  ${CUSTATEVEC_ROOT}/${CUSTATEVEC_LIBDIR}/libcustatevec_static.a
> ```
> 
> and see if it works for you locally.
> 
> You would still configure with `-DCUSTATEVEC_ROOT=/path/to/top/level/cuquantum`. It should add the `12/11` depending on your CUDA install.



> Thank you for the contribution @hamidelmaazouz
> 
> There is another issue with the latest release of cuQuantum as documented in #83. I think that we should consider a combined solution here that will address both your issue and the issue there. I would suggest that you update this PR with the following diff
> 
> ```diff
> diff --git a/runtime/nvqir/custatevec/CMakeLists.txt b/runtime/nvqir/custatevec/CMakeLists.txt
> index b3dd5b0..d9b9250 100644
> --- a/runtime/nvqir/custatevec/CMakeLists.txt
> +++ b/runtime/nvqir/custatevec/CMakeLists.txt
> @@ -10,6 +10,21 @@ set(INTERFACE_POSITION_INDEPENDENT_CODE ON)
>  set (CMAKE_ENABLE_EXPORTS TRUE)
>  message (STATUS "CUSTATEVEC_ROOT and CUDA_FOUND - building custatevec NVQIR backend.")
>  
> +set (CUSTATEVEC_LIBDIR lib)
> +if (EXISTS ${CUSTATEVEC_ROOT}/lib64)
> +  set (CUSTATEVEC_LIBDIR lib64)
> +endif()
> +
> +string(REPLACE "." ";" CUDA_VERSION_LIST ${CMAKE_CUDA_COMPILER_VERSION})
> +list(GET CUDA_VERSION_LIST 0 CUDA_MAJOR_VERSION)
> +
> +find_library(CUSTATEVEC_STATIC_LIB
> +        NAMES custatevec_static
> +        HINTS 
> +          ${CUSTATEVEC_ROOT}/${CUSTATEVEC_LIBDIR} 
> +          ${CUSTATEVEC_ROOT}/${CUSTATEVEC_LIBDIR}/${CUDA_MAJOR_VERSION}
> + )
> +
>  macro (nvqir_create_cusv_plugin LIBRARY_NAME SOURCE_FILENAME) 
>    add_library(${LIBRARY_NAME} SHARED ${SOURCE_FILENAME})
>  
> @@ -17,10 +32,6 @@ macro (nvqir_create_cusv_plugin LIBRARY_NAME SOURCE_FILENAME)
>      PRIVATE .. ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES} ${CMAKE_SOURCE_DIR}/runtime/common
>      ${CUSTATEVEC_ROOT}/include)
>  
> -  set (CUSTATEVEC_LIBDIR lib)
> -  if (EXISTS ${CUSTATEVEC_ROOT}/lib64)
> -    set (CUSTATEVEC_LIBDIR lib64)
> -  endif()
>  
>    target_link_libraries(${LIBRARY_NAME} PRIVATE fmt::fmt-header-only cudaq-common
>                  ${CUSTATEVEC_ROOT}/${CUSTATEVEC_LIBDIR}/libcustatevec_static.a
> ```
> 
> and see if it works for you locally.
> 
> You would still configure with `-DCUSTATEVEC_ROOT=/path/to/top/level/cuquantum`. It should add the `12/11` depending on your CUDA install.

Thank you @amccaskey for the review. The Issue in https://github.com/NVIDIA/cuda-quantum/issues/83 is very similar to mine. @1tnguyen This PR with the review changes solves both problems.

You could try with `CUQUANTUM_INSTALL_PREFIX=/usr bash scripts/build_cudaq.sh`

**Comment by hamidelmaazouz** [comment]
@amccaskey @1tnguyen for https://github.com/NVIDIA/cuda-quantum/issues/83, one would expect Cmake to look into standard system locations by default, but I would also want explicit choice of library location (in case I have  package-based and tarball-based installs). Let me know if you want to add `/usr` (and any other system default location) to the hints list

**Comment by 1tnguyen** [comment]
Thanks @hamidelmaazouz. I've checked out your feature branch and can confirm that it resolves the issue I reported in https://github.com/NVIDIA/cuda-quantum/issues/83.

Testing steps that I did:
- Run a fresh docker with CUDA 12: `docker run -it --gpus all nvidia/cuda:12.1.0-devel-ubuntu20.04`
- Install `cuquantum` via `apt`: `apt install -y cuquantum cuquantum-dev cuquantum-doc` (along with other basic packages for cuda quantum build).
- Build cuda quantum with: `cmake .. -DCUSTATEVEC_ROOT=/usr`

Everything seems to be working as expected.

**Pull request merged**
