### PR TITLE
Renamed static variables (GetCircuitSymbol) for clarity

### PR DESCRIPTION
**Pull request by 1tnguyen**
### Description

`GetCircuitSymbol` static variable name was used for both "getQuantumPlatform" and "getCircuitSimulator" function name lookup, which is a bit unclear. Hence, rename accordingly.

### Checklist:
- [ ] I have added tests to cover my changes. 
Not applicable: should be covered by existing tests.
 - [ ] I have updated the documentation accordingly.
Not applicable: static variables for use locally within a source file, no extra documentation required.
 - [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by 1tnguyen** [comment]
I have read the Contributor License Agreement and I hereby accept the Terms.

**Comment by 1tnguyen** [comment]
recheck

**Comment by amccaskey** [comment]
Thanks for catching this oversight, Thien! Awesome to have a contribution from you. 

@bettinaheim will work to figure out what's going on with the CLA check.

**Comment by bettinaheim** [comment]
@amccaskey @1tnguyen The CLA check is now passing.

Technically, this is a breaking change in the API. Given that it is a simple one and we haven't documented this explicitly, I have no concerns with pulling it in. Let's make sure to capture this in release notes.

**Review by bettinaheim — APPROVED** [review]

**Comment by amccaskey** [comment]
@bettinaheim I'm confused - how is this a breaking API change? This is internal library code, it is never used or seen by front-end programmers.

**Comment by bettinaheim** [comment]
> @bettinaheim I'm confused - how is this a breaking API change? This is internal library code, it is never used or seen by front-end programmers.

GetCircuitSimulatorSymbol and GetQuantumPlatformSymbol are publicly accessible, are they not?

**Comment by amccaskey** [comment]
These are not publicly accessible. The are hidden in implementation files. There is no declaration of them in public headers.

**Comment by bettinaheim** [comment]
> These are not publicly accessible. The are hidden in implementation files. There is no declaration of them in public headers.

Oh, I see what you mean. No need for release notes then - I removed the label.

**Pull request merged**
