### PR TITLE
Downgrading 'pybind11' to version 2.10.4 from version 2.11.1

### PR DESCRIPTION
**Pull request by khalatepradnya**
Reason - the behavior captured in issue https://github.com/NVIDIA/cuda-quantum/issues/1046.

Task:
- [x] Does this diff still work or needs to be adjusted? -  https://github.com/NVIDIA/cuda-quantum/blob/main/tpls/customizations/pybind11/pybind.h.diff : WORKS, but, line numbers have changed, so updated the diff file.

### CODE REVIEW

**Review by bmhowe23 — COMMENTED** [review]
In general this looks good to me, but do you know what caused the CI failure on arm?

**Comment by khalatepradnya** [comment]
> In general this looks good to me, but do you know what caused the CI failure on arm?

It appears to have failed on LLVM checkout `fatal: unable to access 'https://github.com/llvm/llvm-project/': Failed to connect to github.com port 443: Connection timed out`. I am rerunning the step.

**Review by bmhowe23 — APPROVED** [review]
👍

**Pull request merged**
