### PR TITLE
Support iqm-client 14.0 in tests

### PR DESCRIPTION
**Pull request by kukushechkin**
### Description
We've recently released a new version 14.0 of `iqm-client` and the package is now namespaces with `iqm.` prefix so we can put all our tools under the same namespace. In the GitHub Actions pipeline the latest `iqm-client` version is installed, `cuda-quantum` tests fail to import `iqm_client` and skip iqm tests involving mocked IQM server. Importing `iqm.iqm_client` instead will bring those tests back online.

### CODE REVIEW

**Comment by bmhowe23** [comment]
Thanks, @kukushechkin. Are any changes to the following files needed? I suspect not, but just wanted to double check.
- .github/workflows/test_in_devenv.yml
- .github/workflows/integration_tests.yml

**Comment by kukushechkin** [comment]
> Thanks, @kukushechkin. Are any changes to the following files needed? I suspect not, but just wanted to double check.
> 
> * .github/workflows/test_in_devenv.yml
> * .github/workflows/integration_tests.yml

No, no need to update. The first one, `test_in_devenv.yml`, only does `pip install` by package name and `integration_tests.yml` does `cortex-cli` setup with `iqm_client` user name which is unrelated to the `iqm-client` package.

**Review by bmhowe23 — APPROVED** [review]
LGTM. I also tested w/ the new package on my desktop (and setting `-DCUDAQ_TEST_MOCK_SERVERS=TRUE`), and everything worked as expected.

**Pull request merged**
