### PR TITLE
Add `${PREPROCESSOR_DEFINES}` to the `LIBRARY_MODE` compilation path of `nvq++`

### PR DESCRIPTION
**Pull request by 1tnguyen**
### Description

- We have support for `-D<macro>` CLI argument parsing in the `nvq++` script but those arguments are only sent on to the MLIR quake compilation path, not the default `LIBRARY_MODE` path.
I think we switched the default from MLIR -> `LIBRARY_MODE` at some point, hence exposing this.

- Add tests for coverage.

- While on this, I add the `CMAKE_INCLUDE_FLAG_CUDAQ` rule in our cmake config.

Resolved https://github.com/NVIDIA/cuda-quantum/issues/545 and https://github.com/NVIDIA/cuda-quantum/issues/319

### CODE REVIEW

**Comment by mdepasca** [comment]
There may have been a misunderstanding: `CMAKE_CUDAQ_INCLUDE_FLAG` did not solved #545

**Comment by 1tnguyen** [comment]
> There may have been a misunderstanding: `CMAKE_CUDAQ_INCLUDE_FLAG` did not solved #545

@mdepasca The fix for #545 is in the below line (in the `nvq++` script) of this changeset

`run ${CMAKE_FALLBACK_HOST_CXX} ${COMPILER_FLAGS} -DCUDAQ_LIBRARY_MODE ${PREPROCESSOR_DEFINES} ${INCLUDES} -o ${file}.o -c $i`

where we now send on the previously-missing `${PREPROCESSOR_DEFINES}`. 

If possible, would you mind checking that fix on your current CUDA Quantum installation and let us know if it still doesn't work?

**Comment by mdepasca** [comment]
my CUDAQ cmake configuration seems different in the naming. I paste it as well as the compile command generated by cmake

```cmake
# from CMakeCUDAQInformation.cmake
# ...
set(CMAKE_CUDAQ_COMPILE_OBJECT "<CMAKE_CUDAQ_COMPILER> --cmake-host-compiler <CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> -c <SOURCE> -o <OBJECT> ${CUDAQ_COMPILER_EXTRA_FLAGS}")
# ...
```

while the compile command

```bash
/opt/nvidia/cudaq/bin/nvq++ --cmake-host-compiler /opt/llvm/bin/clang++  \ 
-DDATA_DIR=\\\"./data\\\" \  # <-- this is the definition need in the code
-DUSE_CUDAQ \
-I #included dirs \
-c source.cpp -o source.o "
```

I add here that, if the `DATA_DIR` has no value, but is just defined, then it results defined in the code. Hope this helps

**Comment by 1tnguyen** [comment]
Thanks @mdepasca for the detailed information. I didn't manage to reproduce it: in the last [commit](https://github.com/NVIDIA/cuda-quantum/pull/549/commits/9d679ea41efbdb0039bbed59962dad4e29108973), I added an explicit test for the case whereby the predefined macro has a value. Those tests were passed when I ran it before pushing.

Just checking if you've had a chance to try adding `${PREPROCESSOR_DEFINES}` to line 489 of the local file `/opt/nvidia/cudaq/bin/nvq++` to see if it makes any difference.

**Comment by mdepasca** [comment]
> Thanks @mdepasca for the detailed information. I didn't manage to reproduce it: in the last [commit](https://github.com/NVIDIA/cuda-quantum/pull/549/commits/9d679ea41efbdb0039bbed59962dad4e29108973), I added an explicit test for the case whereby the predefined macro has a value. Those tests were passed when I ran it before pushing.
> 
> Just checking if you've had a chance to try adding `${PREPROCESSOR_DEFINES}` to line 489 of the local file `/opt/nvidia/cudaq/bin/nvq++` to see if it makes any difference.

@1tnguyen thanks for the explanation. That indeed worked :). As you suggested I added `${PREPROCESSOR_DEFINES}` at line 488 in local `/opt/nvidia/cudaq/bin/nvq++` as follows:
```bash
run ${CMAKE_FALLBACK_HOST_CXX} ${COMPILER_FLAGS} -DCUDAQ_LIBRARY_MODE ${PREPROCESSOR_DEFINES} ${INCLUDES} -o ${file}.o -c $I 
```

Thanks

**Pull request merged**
