### PR TITLE
Execute IQM integration tests against IQM Resonance

### PR DESCRIPTION
**Pull request by kukushechkin**
### Description

Our new Resonance platform has been live in production for a while now. With its launch, the legacy Cortex Demo environment has become obsolete and now we're finally deprecating https://demo.qc.iqm.fi. This means CUDAQ integration CI needs to be changed.

The change involves:
- using a different url as `IQM_SERVER_URL`, the QPU architecture there is Adonis (it is called Pyrite on the Resonance side),
- obtaining an IQM Resonance Access Token from the and added to the GitHub actions secrets as `IQM_TOKEN` — you will get a separate email with instructions about this,
- `iqm-cortex-cli` is no longer necessary and removed, `IQM_TOKEN` can be passed to CUDAQ via `IQM_TOKENS_FILE`.

### CODE REVIEW

**Comment by bmhowe23** [comment]
@kukushechkin - this looks good to me, but can you please post a new commit that indicates your prior commits are "signed off": https://github.com/NVIDIA/cuda-quantum/pull/2345/checks?check_run_id=32886985210

This is a new step that is required, and in the future, this manual step can be avoided if your commits are made with "git commit -s" to indicate they are "signed off" at the time of the commit.

**Comment by kukushechkin** [comment]
Fixed a typo (it is Pyrit**e**!) and signed off the previous commits.

**Review by bmhowe23 — APPROVED** [review]
Thanks, @kukushechkin!

I have also incorporated the updated secret into our repo.

**Comment by sacpis** [comment]
@kukushechkin Is Adonis still available to test against? We are getting the following integration test failure for `nvq++ -DSYNTAX_CHECK --target iqm --iqm-machine Adonis $filename`

```
what():  IQM QPU architecture mismatch: Adonis != Crystal 5
```

Would you please provide the `IQM_SERVER_URL` for Crystal 5 arch?

**Pull request merged**
