### PR TITLE
Options for OQC Toshiko machine

### PR DESCRIPTION
**Pull request by owen-oqc**
### Description
The current rest helper defaults to the OQC 8 qubit Lucy device. We now want to support 2 devices on the platform including the 32Q Toshiko coaxmon based super conducting qpu.

### CODE REVIEW

**Review by bmhowe23 — COMMENTED** [review]
Hi @owen-oqc - thanks for the changes! If you apply the additional changes from [here](https://gist.github.com/bmhowe23/f0876b12577872eed2c5a9399006891d), it should fix the CI issues. You can download the 3 patch files into your local repo and then run the following:
```bash
$ git am 000*.patch
```
The main issue was just getting `--emulate` option to keep Lucy as the default machine, and the rest of the suggested changes are simple formatting/spelling updates required by our CI.

**Review by bmhowe23 — APPROVED** [review]
LGTM 👍

**Comment by bmhowe23** [comment]
@owen-oqc - I cannot merge main into your branch, so will you please do that? Hopefully we can get it merged after it is up to date with the base branch.

**Comment by owen-oqc** [comment]
> @owen-oqc - I cannot merge main into your branch, so will you please do that? Hopefully we can get it merged after it is up to date with the base branch.

Done

**Pull request merged**
