### PR TITLE
[submodule] Update pybind11

### LINKED ISSUE #1046: Upgrade pybind11 to the latest version
* Using pybind11 version 2.11.0+ results in three test failures in 'eager' mode under 'experimental/python' branch. These tests work as expected with pybind11 version 2.10.4.
* When the behavior is modified either on pybind11 or on CUDA Quantum, upgrade pybind11 to latest version.
* Origin:

> This issue was introduced with the update to pybind11 2.11 (appears to be a pybind bug). pybind version 2.10 and below work. Easiest fix would be to lower to pybind 2.10 until a fix appears in a future version. pybind 2.11 (appears to be a pybind bug). pybind version 2.10 and below work. Easiest fix would be to lower to pybind 2.10 until a fix appears in a future version.

_Originally posted by @amccaskey in https://github.com/NVIDIA/cuda-quantum/pull/1001#discussion_r1426640287_

```[tasklist]
### Tasks
- [x] Identify the changes / commit in pybind11 that introduced change in behavior.
- [ ] Check behavior with latest version of pybind11
- [ ] Triage if fix possible on CUDA Quantum
```

### PR DESCRIPTION
**Pull request by schweitzpgi**
~The local custom mods are no longer required.~ Bump pybind11 up to the latest version on the master branch. It includes some fixes to its cmake files which avoid potential cmake conflicts.

In addition, simplify the use of Python in cmake. Instead of shotgunning find_package(Python) simply add it to the top-level and let that find propagate everywhere. Avoids errors when doing incremental rebuilds.

Fix #1046

### CODE REVIEW

**Comment by khalatepradnya** [comment]
Curious if this issue https://github.com/NVIDIA/cuda-quantum/issues/1046 is still relevant...

**Comment by schweitzpgi** [comment]
> Curious if this issue #1046 is still relevant... [Edit]: May be not since the issue was reported for 'eager' mode which has been removed.

Correct. Since we're not going to support library mode, that disappears. Yay!

**Comment by khalatepradnya** [comment]
> The local custom mods are no longer required.

So, the https://github.com/pybind/pybind11/issues/4537 is fixed or no longer relevant?

**Comment by schweitzpgi** [comment]
> > The local custom mods are no longer required.
> 
> So, the [pybind/pybind11#4537](https://github.com/pybind/pybind11/issues/4537) is fixed or no longer relevant?

That does not appear to be fixed in pybind11. Is there some reason we didn't submit a PR to fix it?

**Comment by khalatepradnya** [comment]
> > > The local custom mods are no longer required.
> > 
> > 
> > So, the [pybind/pybind11#4537](https://github.com/pybind/pybind11/issues/4537) is fixed or no longer relevant?
> 
> That does not appear to be fixed in pybind11. Is there some reason we didn't submit a PR to fix it?
> 
> Added it back for this PR.

Q: Does the patch need to be updated? 
(If apply patch succeeds, then may not be required)

**Review by khalatepradnya — APPROVED** [review]

**Comment by schweitzpgi** [comment]
Circle the airport until release 0.7 is finalized

**Pull request merged**
