### PR TITLE
Various build fixes

### PR DESCRIPTION
**Pull request by bettinaheim**
This PR:
- Sets the toolchain for the docker image to gcc12, since the OpenMP support is not currently enabled in the llvm build
- Uses [BLAS from netlib](https://www.netlib.org/blas/) instead of [OpenBLAS](https://github.com/xianyi/OpenBLAS/tree/v0.3.21) to supply the blas implementation to avoid sporadic issues with the optimizer
- Fixes a missing image name in the deployment

### CODE REVIEW

**Review by amccaskey — APPROVED** [review]
This all looks fine.

**Review by schweitzpgi — APPROVED** [review]

**Pull request merged**
