### PR TITLE
Use MeasurementInterface to simplify some code.

### PR DESCRIPTION
**Pull request by schweitzpgi**

### CODE REVIEW

**Comment by bmhowe23** [comment]
Can this also be used to simply kernel_builder.cpp near lines 636-641?

**Comment by schweitzpgi** [comment]
> Can this also be used to simply kernel_builder.cpp near lines 636-641?

Yes. Do you want to do it?

**Comment by bmhowe23** [comment]
> > Can this also be used to simply kernel_builder.cpp near lines 636-641?
> 
> Yes. Do you want to do it?

Yes, I'll do it. I just have to figure out how to call the `setRegisterName` method on the MeasurementInterface (or, more likely, add it the .td file)

**Comment by schweitzpgi** [comment]
> > > Can this also be used to simply kernel_builder.cpp near lines 636-641?
> > 
> > 
> > Yes. Do you want to do it?
> 
> Yes, I'll do it. I just have to figure out how to call the `setRegisterName` method on the MeasurementInterface (or, more likely, add it the .td file)

Right. That one has to be added to the MeasurementInterface. It's not there yet.

**Review by boschmitt — APPROVED** [review]

**Pull request merged**
