### PR TITLE
[ci] Build things using Release+Assertions rather than Debug to make the

### PR DESCRIPTION
**Pull request by schweitzpgi**
builds faster and the size of the builds smaller.

### CODE REVIEW

**Comment by amccaskey** [comment]
This build error is due to more of the bogus GCC warnings (which are errors now).

**Comment by schweitzpgi** [comment]
> This build error is due to more of the bogus GCC warnings (which are errors now).

So what's the right thing to do here? Disable `-Werror`? It's not immediately clear to me if there is a simple source code change.

**Comment by amccaskey** [comment]
> > This build error is due to more of the bogus GCC warnings (which are errors now).
> 
> So what's the right thing to do here? Disable `-Werror`? It's not immediately clear to me if there is a simple source code change.

I wish we could find a better way. Someone better with CMake may have a solution, but you could do this 
```diff
diff --git a/runtime/cudaq/domains/chemistry/molecule.cpp b/runtime/cudaq/domains/chemistry/molecule.cpp
index fc97027..d7fa6f7 100644
--- a/runtime/cudaq/domains/chemistry/molecule.cpp
+++ b/runtime/cudaq/domains/chemistry/molecule.cpp
@@ -9,8 +9,15 @@
 #include "MoleculePackageDriver.h"
 #include "cudaq/utils/cudaq_utils.h"
 
+#if (defined(__GNUC__) && !defined(__clang__) && !defined(__INTEL_COMPILER))
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wrestrict"
+#endif
 #include <xtensor/xadapt.hpp>
 #include <xtensor/xio.hpp>
+#if (defined(__GNUC__) && !defined(__clang__) && !defined(__INTEL_COMPILER))
+#pragma GCC diagnostic pop
+#endif
```

**Comment by schweitzpgi** [comment]
I'll give that a shot.

**Pull request closed without merging**
