### PR TITLE
Merge experimental/stateHandling branch to main.

### PR DESCRIPTION
**Pull request by schweitzpgi**
This commit squashes all the commits on the experimental/stateHandling branch into a single "mega-commit".

Please double-check that the changes here are what you expect to be merged into main.

### CODE REVIEW

**Comment by schweitzpgi** [comment]
Audit core is #1766

**Review by annagrin — APPROVED** [review]
Python code and cpp changes for it look good to me.

**Review by amccaskey — APPROVED** [review]
lots of great work here +1

**Pull request merged**
