### PR TITLE
[NFC] Make tests in the test directory more uniform.

### PR DESCRIPTION
**Pull request by schweitzpgi**
Flatten the directory structure under the test/NVQPP directory. All the tests in this directory test the nvq++ compiler end-to-end and are expected to PASS.

Remove redundant word "test" from the filenames where possible.

### CODE REVIEW

**Comment by bmhowe23** [comment]
The ones in the integration folder probably need to remain separate because those are the only ones intended to run in the nightly integration CI job.

**Comment by schweitzpgi** [comment]
> The ones in the integration folder probably need to remain separate because those are the only ones intended to run in the nightly integration CI job.

Do you know where the CI goes about sniffing those out?

Everything under `test/` is run every time regression testing is done. Which means I run them all constantly. If there are some tests that are not truly regression tests, they should be moved out of this directory entirely.

**Comment by schweitzpgi** [comment]
I think we need to restructure the .yml file a bit and not hardcode names of tests into the CI scripts.

**Comment by schweitzpgi** [comment]
Added back the original names as symbolic links to avoid breaking the scripts.

**Review by anthony-santana — APPROVED** [review]
I'm curious why we're using `--target quantinuum --emulate` everywhere now? I imagine there's good reason and that I'm just a little out of the loop here. 

This PR also reminds me that I need to do some cleanup and maintenance on the python compiler tests. Thoughts on moving those to their own `test/Python` folder? I could see the argument for or against

**Comment by bmhowe23** [comment]
This change is now causing all the test were previously only in the tests/NVQPP/integration folder that are in both the `tests/NVQPP` and `tests/NVQPP/integration` folder to be run twice.

**Comment by bmhowe23** [comment]
> I'm curious why we're using `--target quantinuum --emulate` everywhere now? I imagine there's good reason and that I'm just a little out of the loop here.

Many of them have been there for a while, but we are indeed growing the number of those types of tests. In my opinion, the general motivation is to make sure all of our tests can go down to the appropriate QIR representation and be properly executed.  We may have more Quantinuum tests right now due to the recent implementation of the Adaptive Profile because Quantinuum is currently the only provider that supports that.

One additional note: our backends all started out with almost the same pass pipeline, but they are diverging as we update our code base to support the unique capabilities and limitations of each backend. So ideally, every one of our NVQPP tests would target all of our supported backends w/ emulation in order to properly test all of our pass pipeline configurations.

**Pull request merged**
