### PR TITLE
[stateHandling] Fix bug in guard

### PR DESCRIPTION
**Pull request by schweitzpgi**
~Fixes failures in some python tests.~

### CODE REVIEW

**Comment by amccaskey** [comment]
what were the test failures before this?

**Comment by schweitzpgi** [comment]
> what were the test failures before this?

This patch is cherry picking changes I made to main to merge the codegen dialect. I am not sure all of this was really needed. Let me try to whittle it down. There was a multithreading issue that contributed to the dialect not loading that Thien had fixed on the stateHandling branch.

**Review by 1tnguyen — APPROVED** [review]
👍

**Pull request merged**
