### PR TITLE
Use cmake property to gather dependencies for test

### PR DESCRIPTION
**Pull request by Yaraslaut**
### Description

Closes https://github.com/NVIDIA/cuda-quantum/issues/956

Introduced cmake property `CUDAQ_RUNTIME_LIBS` to specify required libraries to build tests

### CODE REVIEW

**Comment by Yaraslaut** [comment]
I have read the Contributor License Agreement and I hereby accept the Terms.

recheck

**Comment by bmhowe23** [comment]
@Yaraslaut would you mind trying to respond "I have read the Contributor License Agreement and I hereby accept the Terms." in a comment all by itself?

**Comment by Yaraslaut** [comment]
I have read the Contributor License Agreement and I hereby accept the Terms.

**Review by schweitzpgi — APPROVED** [review]
Thanks for the change.

**Pull request merged**
