### PR TITLE
Documentation updates for 0.5 release

### LINKED ISSUE #845: Documentation Changes
### Required prerequisites

- [X] Make sure you've read the [documentation](https://nvidia.github.io/cuda-quantum/latest). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/NVIDIA/cuda-quantum/issues) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] If possible, make a PR with a failing test to give us a starting point to work on!

### Describe the bug

A few minor issues/suggestions on CUDA Quantum documentation (updated list to indicate which ones are already done):
- [x] Getting Started -> Use CUDA Quantum in a Terminal: 'replacing <image_name> with the name and tag of the image you downloaded' - I suggest adding an explanation on how to find the image tag and what will be a good default tag to use (latest stable). I also suggest changing the example to latest stable instead of the latest nightly.
- [ ] Learn the Basics -> What is a CUDA Quantum Kernel: 'see the specification for more details' - suggest adding a link to the specific specification page. (Same for other places in the documentation that refers to the specification)
- [ ] Learn the Basics -> Creating Kernels Dynamically: the title says cudaq::kernel_builder but the code calls cudaq::make_kernel.
- [ ] Learn the Basics -> Multi-processor platform: 'Last but not least, the compiled executable (C++) or Python script needs to be launched with an appropriate MPI command, e.g., mpirun, mpiexec, srun, etc.' - an example will be useful.
- [ ] For all tutorials: Add output snippets for each code example.
- [x] Examples -> C++ -> Simulations with cuQuantum - the text talks about 30 qubits but the code has 28.

### Steps to reproduce the bug

Navigate to the page mentioned in the description

### Expected behavior

Mentioned in description

### Is this a regression? If it is, put the last known working version (or commit) here.

Not a regression

### Environment

- **CUDA Quantum version**: Public documentation: https://nvidia.github.io/cuda-quantum/latest/index.html 
- **Python version**: 
- **C++ compiler**: 
- **Operating system**: 

### Suggestions

_No response_

### PR DESCRIPTION
**Pull request by anthony-santana**
### Description

Closes #845
Partially addresses #704 (does not add chemistry/hardware efficient ansatz docs)

### CODE REVIEW

**Comment by bettinaheim** [comment]
@anthony-santana I done see the methods `num_hwe_parameters` and `hwe` listed in the current docs. To close #704, could you please add them?

**Comment by khalatepradnya** [comment]
Looking good.
Curious about the whitespace / line ending changes appearing on multiple lines... what's the reason?

**Review by bettinaheim — APPROVED** [review]

**Pull request merged**
