### PR TITLE
Fix the comment in intro.py example #1497

### LINKED ISSUE #1497: Fix the comment in intro.py example
The comments preceding the `qubit = cudaq.qubit()` referring to `qalloc` are inconsistent with the line of the code.

```
# Next, we can allocate qubits to the kernel via `qalloc(qubit_count)`.
# An empty call to `qalloc` will return a single qubit.
qubit = cudaq.qubit()
```

### PR DESCRIPTION
**Pull request by Gaurang-Belekar**
### Description

Fixed the comment in intro.py example, 
[Issue #1497](https://github.com/NVIDIA/cuda-quantum/issues/1497)

```# Next, we can allocate qubits to the kernel via `qalloc(qubit_count)`.```
```# An empty call to `qalloc` will return a single qubit.```
```qubit = cudaq.qubit()```

To

 ```# Allocates qubit to |0> state```
  ```qubit = cudaq.qubit()```

Fixes #1497

### CODE REVIEW

**Comment by Gaurang-Belekar** [comment]
I have read the Contributor License Agreement and I hereby accept the Terms.

**Comment by poojarao8** [comment]
This PR needs help with issue as stated in https://github.com/NVIDIA/cuda-quantum/discussions/1530.

**Comment by Gaurang-Belekar** [comment]
@poojarao8 I have changed the comment accordingly, 
``` # Next, we can allocate a single qubit to the kernel via `qubit()`. ```
``` qubit = cudaq.qubit() ```

Earlier I referred to the comment mention in other files while intalising. Made relevant changes in the above commit. Also it is showing 'the dev environment build pending for approval'.

**Review by bmhowe23 — APPROVED** [review]
Thanks @Gaurang-Belekar!

**Pull request merged**
