### PR TITLE
Base Profile: Provide default register name when one doesn't exist

### PR DESCRIPTION
**Pull request by amccaskey**
Provide a default global register name for the base profile result_record_output in the absence of one (i.e. don't just default to `i8* null`).

### CODE REVIEW

**Review by schweitzpgi — COMMENTED** [review]
It feels weird to me to hack around a bug in the target's base profile processing.

**Comment by amccaskey** [comment]
> It feels weird to me to hack around a bug in the target's base profile processing.

I think that we've moved from it being a bug, to it's something they disallow. They don't allow that second argument to be null any more. 

The real bug is in not being able to parse the global variable name and requiring that it be a specified name (`@0`, `@1`, etc). This bug will be fixed next week int the target server.

**Comment by schweitzpgi** [comment]
> > It feels weird to me to hack around a bug in the target's base profile processing.
> 
> I think that we've moved from it being a bug, to it's something they disallow. They don't allow that second argument to be null any more.
> 
> The real bug is in not being able to parse the global variable name and requiring that it be a specified name (`@0`, `@1`, etc). This bug will be fixed next week int the target server.

If this is true, then the QIR spec needs to be updated and we need to mandate that the user specify names everywhere, no? If the names are optional in any sense, then the target will have to deal with them being optional by definition.

**Comment by bettinaheim** [comment]
> If this is true, then the QIR spec needs to be updated and we need to mandate that the user specify names everywhere, no? If the names are optional in any sense, then the target will have to deal with them being optional by definition.

@schweitzpgi The spec mandates a non-null argument:
"For all output recording functions, the i8* argument must be a non-null pointer to a global constant that contains a null-terminated string. A unique string must be used for each call to an output recording function within the same entry point. "

**Comment by schweitzpgi** [comment]
> > If this is true, then the QIR spec needs to be updated and we need to mandate that the user specify names everywhere, no? If the names are optional in any sense, then the target will have to deal with them being optional by definition.
> 
> @schweitzpgi The spec mandates a non-null argument: "For all output recording functions, the i8* argument must be a non-null pointer to a global constant that contains a null-terminated string. A unique string must be used for each call to an output recording function within the same entry point. "

Are you citing some text from https://github.com/qir-alliance/qir-spec/tree/main ? If so, I can't find that in specification 0.1.

**Pull request closed without merging**
