### PR TITLE
Update quantum_operations.rst for missing ket vector notation

### PR DESCRIPTION
**Pull request by wahorvat**
### Description

Updated 0 / 1 to ket notation under both Quantum Gates and Measurements. Assumed kets were intended to match the subsequent code example and mathematical explanation of probabilities.

### CODE REVIEW

**Comment by wahorvat** [comment]
I have read the Contributor License Agreement and I hereby accept the Terms.

**Review by bmhowe23 — APPROVED** [review]
Thanks, @wahorvat!

**Pull request merged**
