### PR TITLE
[stateHandling] merge main branch commits

### PR DESCRIPTION
**Pull request by schweitzpgi**
DO NOT SQUASH THESE COMMITS!

### CODE REVIEW

**Review by bmhowe23 — APPROVED** [review]

**Comment by schweitzpgi** [comment]
This PR should have used "rebase-and-merge" to keep the commit history together, but that engineering option is disabled. Instead I used the "merge commit" form of merging which interleaves the histories of the branches like shuffling 2 decks of cards together, which is a mess to decipher.

**Pull request merged**
